gui:
  sidePanelWidth: 0.25
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - '#efefef' 
  showBottomLine: false
  showRandomTip: false
  showFileTree: false
git:
  paging: 
    colorArg: always
    pager: delta --dark --paging=never --side-by-side  
promptToReturnFromSubprocess: false
showCommandLog: false
os:
  openCommand: 'nvim -d {{filename}}'
